#include <nodehammer/export/obj_exporter.hpp>
#include <nodehammer/ir/diagnostic_codes.hpp>

#include <glm/glm.hpp>
#include <glm/gtc/matrix_inverse.hpp>

#include <format>
#include <fstream>
#include <queue>
#include <unordered_map>

namespace nodehammer {

std::string_view ObjExporter::formatName() const noexcept { return "obj"; }

std::vector<std::string> ObjExporter::supportedExtensions() const { return {".obj"}; }

ExportResult ObjExporter::write(const RenderScene &scene, const std::filesystem::path &path,
                                const ExportConfig &config) const {
    ExportResult result;

    std::ofstream objFile{path};
    if (!objFile) {
        result.diags.error(codes::kErrExportWriteFailed,
                           std::format("failed to open '{}' for writing", path.string()),
                           path.string());
        return result;
    }

    const auto mtlPath = path.parent_path() / (path.stem().string() + ".mtl");
    std::ofstream mtlFile{mtlPath};
    if (!mtlFile) {
        result.diags.error(codes::kErrExportWriteFailed,
                           std::format("failed to open '{}' for writing", mtlPath.string()),
                           mtlPath.string());
        return result;
    }

    objFile << "# Generated by nodehammer\n";
    objFile << "mtllib " << mtlPath.filename().string() << "\n\n";
    mtlFile << "# Generated by nodehammer\n\n";

    // ── Write MTL ─────────────────────────────────────────────────────────────

    std::unordered_map<RenderMaterialId, std::string> matNames;
    for (const auto &[id, mat] : scene.materials) {
        mtlFile << "newmtl " << mat.name << "\n";
        mtlFile << "Kd " << mat.baseColorFactor.r << " " << mat.baseColorFactor.g << " "
                << mat.baseColorFactor.b << "\n";
        // PBR metallic → OBJ specular: rough approximation
        const float s = mat.metallicFactor;
        mtlFile << "Ks " << s << " " << s << " " << s << "\n";
        if (mat.baseColorFactor.a < 1.0f)
            mtlFile << "d " << mat.baseColorFactor.a << "\n";
        if (glm::any(glm::notEqual(mat.emissiveFactor, glm::vec3{0.f})))
            mtlFile << "Ke " << mat.emissiveFactor.r << " " << mat.emissiveFactor.g << " "
                    << mat.emissiveFactor.b << "\n";
        mtlFile << "\n";
        matNames[id] = mat.name;
    }

    // ── Write geometry — BFS from root, world-space ───────────────────────────

    if (scene.nodes.empty() || !scene.nodes.contains(scene.rootId))
        return result;

    std::size_t vtxOffset = 0; // running 1-based index base

    std::queue<RenderNodeId> q;
    q.push(scene.rootId);

    while (!q.empty()) {
        const RenderNodeId rnId = q.front();
        q.pop();
        if (!scene.nodes.contains(rnId))
            continue;
        const RenderNode &rn = scene.nodes.at(rnId);

        for (const auto &binding : rn.meshBindings) {
            if (!scene.meshAssets.contains(binding.meshId))
                continue;
            const MeshAsset &ma = scene.meshAssets.at(binding.meshId);
            if (ma.vertices.empty())
                continue;

            objFile << "o " << rn.name << "\n";
            if (matNames.contains(binding.materialId))
                objFile << "usemtl " << matNames.at(binding.materialId) << "\n";

            // Normal transform: inverse-transpose of worldTransform (upper-left 3×3)
            const glm::mat4 &world = rn.worldTransform;
            const glm::mat3 normalMat = glm::mat3(glm::transpose(glm::affineInverse(world)));

            const float s = static_cast<float>(config.unitScale);
            for (const auto &v : ma.vertices) {
                const glm::vec4 wpos = world * glm::vec4(v.position, 1.0f);
                objFile << "v " << wpos.x * s << " " << wpos.y * s << " " << wpos.z * s << "\n";
            }
            for (const auto &v : ma.vertices) {
                const glm::vec3 wn = glm::normalize(normalMat * v.normal);
                objFile << "vn " << wn.x << " " << wn.y << " " << wn.z << "\n";
            }

            for (std::size_t i = 0; i + 2 < ma.indices.size(); i += 3) {
                const std::size_t i0 = ma.indices[i + 0] + 1 + vtxOffset;
                const std::size_t i1 = ma.indices[i + 1] + 1 + vtxOffset;
                const std::size_t i2 = ma.indices[i + 2] + 1 + vtxOffset;
                objFile << "f " << i0 << "//" << i0 << " " << i1 << "//" << i1 << " " << i2 << "//"
                        << i2 << "\n";
            }

            vtxOffset += ma.vertices.size();
            objFile << "\n";
        }

        for (const auto childId : rn.children)
            q.push(childId);
    }

    return result;
}

} // namespace nodehammer
