// Does the Lua config front end work in a browser?
//
// `nodehammer_tests` already covers the front end itself, and under Emscripten
// it now runs those cases too — but it links with -sNODERAWFS, which hands the
// wasm module the host's real filesystem. No browser has that. So a suite that
// is green there has answered "does this work under node", which is a weaker
// question than the one worth asking.
//
// This binary is the same code linked without NODERAWFS: the only filesystem is
// MEMFS, exactly what a tab gets. Everything a script reads has to be written
// into it first, which is also true of any project front end that will
// eventually stage a config out of a .nhproj.
//
// It goes through the public `Config::read` rather than `evalLuaConfig`, because
// the extension dispatch is part of what is being claimed to work, and because a
// browser caller has no other door. Catch2 is deliberately absent: this is one
// link configuration proving one property, and it is driven by ctest via node.

#include <nodehammer/build.hpp>
#include <nodehammer/config.hpp>
#include <nodehammer/diagnostics.hpp>
#include <nodehammer/semantic_scene.hpp>

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>

namespace nh = nodehammer;

namespace {

int failures = 0;

void check(bool ok, std::string_view what) {
    std::cout << (ok ? "  ok   " : "  FAIL ") << what << "\n";
    if (!ok) {
        ++failures;
    }
}

void put(const std::filesystem::path &p, std::string_view content) {
    std::filesystem::create_directories(p.parent_path());
    std::ofstream out(p, std::ios::binary);
    out << content;
}

/// Read a `.lua` config, reporting the thrown code instead of the config when it
/// does not load.
struct ReadOutcome {
    bool ok{false};
    std::string code;
};

ReadOutcome read(const std::filesystem::path &path) {
    try {
        const auto result = nh::Config::read(path);
        return {result.config.valid(), {}};
    } catch (const nh::Error &e) {
        return {false, std::string{e.code()}};
    }
}

} // namespace

int main() {
    const std::filesystem::path root = "/work";

    // 1. The capability query answers the same thing here as on a desktop. This
    //    is the regression the old build gate produced: same source tree, two
    //    different public answers depending on the target.
    const auto formats = nh::Config::formats();
    check(std::ranges::find(formats, "lua") != formats.end(), "formats() lists lua in wasm");

    // 2. A script that uses the parts of Lua a config is written in Lua *for* —
    //    a fragment pulled in by include(), and rules generated by a loop.
    put(root / "materials.lua", R"LUA(
material("silicon", { metallic = 1.0, roughness = 0.05 })
)LUA");
    put(root / "main.lua", R"LUA(
config { deduplicate_shapes = true }
include("materials.lua")
for i = 1, 3 do
  rule { match = ('path ~= "**/Layer%d*"'):format(i), material = "silicon" }
end
)LUA");

    const auto sound = read(root / "main.lua");
    check(sound.ok, "Config::read evaluates a .lua staged in MEMFS");

    // 3. That it parsed proves nothing about whether what it produced arrives.
    //    A selection rule dropping everything is observable through a public
    //    verb: `applySelection` cannot deliver a pruned scene, so it throws
    //    NH0401 — which it can only do if the script's rules reached the config
    //    that reached the pipeline.
    put(root / "drop_all.lua", R"LUA(
drop { 'path ~= "**"' }
)LUA");
    const auto dropping = read(root / "drop_all.lua");
    check(dropping.ok, "Config::read accepts a selection script");

    if (dropping.ok) {
        const auto scene = nh::SemanticScene::read("", nh::SemanticScene::ReadOptions{"synthetic"});
        const auto config = nh::Config::read(root / "drop_all.lua");
        std::string thrown;
        try {
            (void)nh::applySelection(scene.scene, config.config.scene());
        } catch (const nh::Error &e) {
            thrown = std::string{e.code()};
        }
        check(thrown == "NH0401", "the script's rules reach the pipeline (NH0401)");
    }

    // 4. The characteristic browser failure: a script whose include target was
    //    never staged. It has to be reported, not crashed on — MEMFS makes this
    //    the common case rather than a corner one, since nothing is there unless
    //    something put it there.
    put(root / "orphan.lua", "include(\"never_staged.lua\")\n");
    const auto orphan = read(root / "orphan.lua");
    check(!orphan.ok, "an unstaged include is reported, not crashed on");

    // 5. And a path that does not exist at all still fails as a missing file,
    //    the way it does for TOML.
    const auto missing = read(root / "no_such_config.lua");
    check(!missing.ok && missing.code == "NH0100", "a missing .lua is NH0100");

    std::cout << (failures == 0 ? "wasm lua smoke: OK\n" : "wasm lua smoke: FAILED\n");
    return failures == 0 ? 0 : 1;
}
