#include <nodehammer/viewer/app.hpp>

#include "imgui_impl_bgfx.hpp"
#include "sdl_platform.hpp"

// Suppress renderer profiles we never compile so BGFX_EMBEDDED_SHADER doesn't
// reference symbols (e.g. `_dx11`, `_dxil`) that the build system never
// produced. Keep ESSL/GLSL/SPIRV/METAL on their bgfx defaults — those match
// the profiles bgfx_compile_shaders emits for this project's target list.
#define BGFX_PLATFORM_SUPPORTS_DXBC 0
#define BGFX_PLATFORM_SUPPORTS_DXIL 0
#define BGFX_PLATFORM_SUPPORTS_NVN 0
#define BGFX_PLATFORM_SUPPORTS_PSSL 0
#define BGFX_PLATFORM_SUPPORTS_WGSL 0

#include <SDL3/SDL.h>
#include <bgfx/bgfx.h>
#include <bgfx/embedded_shader.h>
#include <bgfx/platform.h>
#include <bx/math.h>
#include <bx/platform.h>
#include <imgui.h>
#include <imgui_impl_sdl3.h>

#ifdef __EMSCRIPTEN__
#include <emscripten/emscripten.h>
#include <emscripten/html5.h>
#endif

// Per-profile shader bytecode arrays generated by shaders/CMakeLists.txt.
#if BGFX_PLATFORM_SUPPORTS_GLSL
#include "glsl/fs_solid.sc.bin.h"
#include "glsl/vs_solid.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_ESSL
#include "essl/fs_solid.sc.bin.h"
#include "essl/vs_solid.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_SPIRV
#include "spirv/fs_solid.sc.bin.h"
#include "spirv/vs_solid.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_METAL
#include "metal/fs_solid.sc.bin.h"
#include "metal/vs_solid.sc.bin.h"
#endif

#include <print>
#include <stdexcept>

namespace nodehammer::viewer {

namespace {

const bgfx::EmbeddedShader k_solid_shaders[] = {
    BGFX_EMBEDDED_SHADER(vs_solid),
    BGFX_EMBEDDED_SHADER(fs_solid),
    BGFX_EMBEDDED_SHADER_END(),
};

struct PosColorVertex {
    float x, y, z;
    uint32_t abgr;
};

bgfx::VertexLayout pos_color_layout() {
    bgfx::VertexLayout l;
    l.begin()
        .add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Uint8, true)
        .end();
    return l;
}

constexpr bgfx::ViewId k_view_scene = 0;
constexpr bgfx::ViewId k_view_imgui = 1;

} // namespace

struct App::Impl {
    Config cfg;
    SDL_Window *window{nullptr};
    uint32_t fb_width{0};
    uint32_t fb_height{0};
    bool quit{false};

    bgfx::ProgramHandle program = BGFX_INVALID_HANDLE;
    bgfx::VertexBufferHandle vbh = BGFX_INVALID_HANDLE;
    bgfx::IndexBufferHandle ibh = BGFX_INVALID_HANDLE;

    uint64_t frame_count{0};
    uint64_t last_fps_tick{0};
    float fps{0.f};

    explicit Impl(Config c) : cfg(std::move(c)) {}

    void init_sdl();
    void init_bgfx();
    void init_imgui();
    void init_geometry();
    void shutdown();
    void poll_events();
    void resize_if_needed();
    void render();
    void tick();

#ifdef __EMSCRIPTEN__
    static void em_tick(void *self) { static_cast<Impl *>(self)->tick(); }
#endif
};

void App::Impl::init_sdl() {
    if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS)) {
        throw std::runtime_error(std::string{"SDL_Init failed: "} + SDL_GetError());
    }
    window = SDL_CreateWindow(cfg.title.c_str(), static_cast<int>(cfg.width),
                              static_cast<int>(cfg.height),
                              SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY);
    if (window == nullptr) {
        throw std::runtime_error(std::string{"SDL_CreateWindow failed: "} + SDL_GetError());
    }
    int w = 0, h = 0;
    SDL_GetWindowSizeInPixels(window, &w, &h);
    fb_width = static_cast<uint32_t>(w);
    fb_height = static_cast<uint32_t>(h);
}

void App::Impl::init_bgfx() {
    bgfx::PlatformData pd{};
    if (!fill_platform_data(window, pd)) {
        throw std::runtime_error("Failed to fill bgfx platform data from SDL window");
    }
    // Single-threaded init: must call renderFrame before init on threads where
    // bgfx will own the context. Skipped here — we run single-threaded throughout
    // (especially required on emscripten).
    bgfx::renderFrame();

    bgfx::Init init;
    init.platformData = pd;
#ifdef __EMSCRIPTEN__
    init.type = bgfx::RendererType::OpenGLES;
#else
    init.type = bgfx::RendererType::Count; // auto-pick
#endif
    init.resolution.width = fb_width;
    init.resolution.height = fb_height;
    init.resolution.reset = cfg.vsync ? BGFX_RESET_VSYNC : BGFX_RESET_NONE;
    if (!bgfx::init(init)) {
        throw std::runtime_error("bgfx::init failed");
    }

    bgfx::setViewClear(k_view_scene, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH, 0x202830ff, 1.0f, 0);
    bgfx::setViewRect(k_view_scene, 0, 0, bgfx::BackbufferRatio::Equal);
}

void App::Impl::init_imgui() {
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO &io = ImGui::GetIO();
    io.IniFilename = nullptr; // don't write imgui.ini next to the binary
    ImGui::StyleColorsDark();

    if (!ImGui_ImplSDL3_InitForOther(window)) {
        throw std::runtime_error("ImGui_ImplSDL3_InitForOther failed");
    }
    if (!ImGui_Implbgfx_Init(k_view_imgui)) {
        throw std::runtime_error("ImGui_Implbgfx_Init failed");
    }
}

void App::Impl::init_geometry() {
    static const PosColorVertex k_verts[] = {
        {0.0f, 0.5f, 0.0f, 0xff0000ff},   // top, red
        {0.5f, -0.5f, 0.0f, 0xff00ff00},  // bottom-right, green
        {-0.5f, -0.5f, 0.0f, 0xffff0000}, // bottom-left, blue
    };
    static const uint16_t k_indices[] = {0, 1, 2};

    const bgfx::VertexLayout layout = pos_color_layout();
    vbh = bgfx::createVertexBuffer(bgfx::makeRef(k_verts, sizeof(k_verts)), layout);
    ibh = bgfx::createIndexBuffer(bgfx::makeRef(k_indices, sizeof(k_indices)));

    const bgfx::RendererType::Enum type = bgfx::getRendererType();
    program =
        bgfx::createProgram(bgfx::createEmbeddedShader(k_solid_shaders, type, "vs_solid"),
                            bgfx::createEmbeddedShader(k_solid_shaders, type, "fs_solid"), true);
    if (!bgfx::isValid(program)) {
        throw std::runtime_error("Failed to create solid shader program");
    }
}

void App::Impl::shutdown() {
    if (bgfx::isValid(program)) {
        bgfx::destroy(program);
    }
    if (bgfx::isValid(vbh)) {
        bgfx::destroy(vbh);
    }
    if (bgfx::isValid(ibh)) {
        bgfx::destroy(ibh);
    }
    ImGui_Implbgfx_Shutdown();
    ImGui_ImplSDL3_Shutdown();
    ImGui::DestroyContext();
    bgfx::shutdown();
    if (window != nullptr) {
        SDL_DestroyWindow(window);
        window = nullptr;
    }
    SDL_Quit();
}

void App::Impl::poll_events() {
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
        ImGui_ImplSDL3_ProcessEvent(&ev);
        switch (ev.type) {
        case SDL_EVENT_QUIT:
            quit = true;
            break;
        case SDL_EVENT_WINDOW_CLOSE_REQUESTED:
            if (ev.window.windowID == SDL_GetWindowID(window)) {
                quit = true;
            }
            break;
        default:
            break;
        }
    }
}

void App::Impl::resize_if_needed() {
    int w = 0, h = 0;
    SDL_GetWindowSizeInPixels(window, &w, &h);
    if (w <= 0 || h <= 0) {
        return;
    }
    const uint32_t uw = static_cast<uint32_t>(w);
    const uint32_t uh = static_cast<uint32_t>(h);
    if (uw == fb_width && uh == fb_height) {
        return;
    }
    fb_width = uw;
    fb_height = uh;
    bgfx::reset(fb_width, fb_height, cfg.vsync ? BGFX_RESET_VSYNC : BGFX_RESET_NONE);
    bgfx::setViewRect(k_view_scene, 0, 0, bgfx::BackbufferRatio::Equal);
}

void App::Impl::render() {
    bgfx::touch(k_view_scene);

    // Camera: simple fixed view down the -Z axis.
    const bgfx::Caps *caps = bgfx::getCaps();
    float view[16];
    float proj[16];
    const bx::Vec3 eye = {0.f, 0.f, -3.f};
    const bx::Vec3 at = {0.f, 0.f, 0.f};
    const bx::Vec3 up = {0.f, 1.f, 0.f};
    bx::mtxLookAt(view, eye, at, up);
    bx::mtxProj(proj, 60.0f, static_cast<float>(fb_width) / static_cast<float>(fb_height), 0.1f,
                100.f, caps->homogeneousDepth);
    bgfx::setViewTransform(k_view_scene, view, proj);

    // Spin the triangle slowly so we can see frames advancing.
    const float t = static_cast<float>(SDL_GetTicks()) * 0.001f;
    float mtx[16];
    bx::mtxRotateY(mtx, t * 0.6f);
    bgfx::setTransform(mtx);

    bgfx::setVertexBuffer(0, vbh);
    bgfx::setIndexBuffer(ibh);
    bgfx::setState(BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A | BGFX_STATE_WRITE_Z |
                   BGFX_STATE_DEPTH_TEST_LESS | BGFX_STATE_MSAA);
    bgfx::submit(k_view_scene, program);
}

void App::Impl::tick() {
    poll_events();
    resize_if_needed();

    ImGui_Implbgfx_NewFrame();
    ImGui_ImplSDL3_NewFrame();
    ImGui::NewFrame();

    {
        // Update FPS roughly once per second.
        const uint64_t now = SDL_GetTicks();
        ++frame_count;
        if (last_fps_tick == 0) {
            last_fps_tick = now;
        }
        if (now - last_fps_tick >= 1000) {
            fps =
                static_cast<float>(frame_count) * 1000.f / static_cast<float>(now - last_fps_tick);
            frame_count = 0;
            last_fps_tick = now;
        }
    }

    ImGui::Begin("nodehammer viewer");
    ImGui::Text("Stage 1: hello triangle");
    ImGui::Text("Backbuffer: %u x %u", fb_width, fb_height);
    ImGui::Text("Renderer: %s", bgfx::getRendererName(bgfx::getRendererType()));
    ImGui::Text("FPS: %.1f", fps);
    ImGui::End();

    render();

    ImGui::Render();
    ImGui_Implbgfx_RenderDrawData(ImGui::GetDrawData());

    bgfx::frame();
}

App::App(Config cfg) : impl_(std::make_unique<Impl>(std::move(cfg))) {
    impl_->init_sdl();
    impl_->init_bgfx();
    impl_->init_imgui();
    impl_->init_geometry();
}

App::~App() {
    if (impl_) {
        impl_->shutdown();
    }
}

int App::run() {
#ifdef __EMSCRIPTEN__
    // simulate_infinite_loop=1 unwinds main() with an exception so the runtime
    // keeps the wasm instance + GL context alive between frames. Requires
    // -fwasm-exceptions, which is set globally for emscripten builds.
    emscripten_set_main_loop_arg(&App::Impl::em_tick, impl_.get(), 0, 1);
    return 0;
#else
    while (!impl_->quit) {
        impl_->tick();
    }
    return 0;
#endif
}

} // namespace nodehammer::viewer
