#include <nodehammer/viewer/app.hpp>

#include "imgui_impl_bgfx.hpp"
#include "sdl_platform.hpp"

#include <nodehammer/ir/render.hpp>
#include <nodehammer/viewer/camera.hpp>
#include <nodehammer/viewer/scene_renderer.hpp>

// Suppress renderer profiles we never compile so BGFX_EMBEDDED_SHADER doesn't
// reference symbols (e.g. `_dx11`, `_dxil`) that the build system never
// produced. Keep ESSL/GLSL/SPIRV/METAL on their bgfx defaults — those match
// the profiles bgfx_compile_shaders emits for this project's target list.
#define BGFX_PLATFORM_SUPPORTS_DXBC 0
#define BGFX_PLATFORM_SUPPORTS_DXIL 0
#define BGFX_PLATFORM_SUPPORTS_NVN 0
#define BGFX_PLATFORM_SUPPORTS_PSSL 0
#define BGFX_PLATFORM_SUPPORTS_WGSL 0

#include <SDL3/SDL.h>
#include <bgfx/bgfx.h>
#include <bgfx/embedded_shader.h>
#include <bgfx/platform.h>
#include <bx/math.h>
#include <bx/platform.h>
#include <imgui.h>
#include <imgui_impl_sdl3.h>

#ifdef __EMSCRIPTEN__
#include <emscripten/emscripten.h>
#include <emscripten/html5.h>
#endif

// Per-profile shader bytecode arrays generated by shaders/CMakeLists.txt.
#if BGFX_PLATFORM_SUPPORTS_GLSL
#include "glsl/fs_solid.sc.bin.h"
#include "glsl/vs_solid.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_ESSL
#include "essl/fs_solid.sc.bin.h"
#include "essl/vs_solid.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_SPIRV
#include "spirv/fs_solid.sc.bin.h"
#include "spirv/vs_solid.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_METAL
#include "metal/fs_solid.sc.bin.h"
#include "metal/vs_solid.sc.bin.h"
#endif

#include <cmath>
#include <print>
#include <stdexcept>

namespace nodehammer::viewer {

namespace {

const bgfx::EmbeddedShader k_solid_shaders[] = {
    BGFX_EMBEDDED_SHADER(vs_solid),
    BGFX_EMBEDDED_SHADER(fs_solid),
    BGFX_EMBEDDED_SHADER_END(),
};

struct PosColorVertex {
    float x, y, z;
    uint32_t abgr;
};

bgfx::VertexLayout pos_color_layout() {
    bgfx::VertexLayout l;
    l.begin()
        .add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Uint8, true)
        .end();
    return l;
}

constexpr bgfx::ViewId k_view_scene = 0;
constexpr bgfx::ViewId k_view_imgui = 1;

} // namespace

struct App::Impl {
    Config cfg;
    SDL_Window *window{nullptr};
    uint32_t fb_width{0};
    uint32_t fb_height{0};
    bool quit{false};

    bgfx::ProgramHandle program = BGFX_INVALID_HANDLE;
    bgfx::VertexBufferHandle vbh = BGFX_INVALID_HANDLE;
    bgfx::IndexBufferHandle ibh = BGFX_INVALID_HANDLE;

    // Stage 3: scene state. When `scene` is non-null we draw it via
    // `scene_renderer` and skip the demo triangle.
    std::shared_ptr<const RenderScene> scene;
    SceneRenderer scene_renderer;
    Camera camera;
    bool scene_uploaded{false};
    bool camera_framed{false};

    // Debug toggles surfaced through the ImGui panel.
    bool show_debug_stats{false};
    bool wireframe{false};
    bool cull_back{false};

    // Mouse state for camera control. Buttons are queried from io.MouseDown.
    bool mouse_held_left{false};
    bool mouse_held_middle{false};

    uint64_t frame_count{0};
    uint64_t last_fps_tick{0};
    float fps{0.f};

    explicit Impl(Config c) : cfg(std::move(c)) {}

    void init_sdl();
    void init_bgfx();
    void init_imgui();
    void init_geometry();
    void shutdown();
    void poll_events();
    void update_camera_input();
    void resize_if_needed();
    void render();
    void tick();

#ifdef __EMSCRIPTEN__
    static void em_tick(void *self) { static_cast<Impl *>(self)->tick(); }
#endif
};

void App::Impl::init_sdl() {
    if (!SDL_Init(SDL_INIT_VIDEO | SDL_INIT_EVENTS)) {
        throw std::runtime_error(std::string{"SDL_Init failed: "} + SDL_GetError());
    }
    window = SDL_CreateWindow(cfg.title.c_str(), static_cast<int>(cfg.width),
                              static_cast<int>(cfg.height),
                              SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY);
    if (window == nullptr) {
        throw std::runtime_error(std::string{"SDL_CreateWindow failed: "} + SDL_GetError());
    }
    int w = 0, h = 0;
    SDL_GetWindowSizeInPixels(window, &w, &h);
    fb_width = static_cast<uint32_t>(w);
    fb_height = static_cast<uint32_t>(h);
}

void App::Impl::init_bgfx() {
    bgfx::PlatformData pd{};
    if (!fill_platform_data(window, pd)) {
        throw std::runtime_error("Failed to fill bgfx platform data from SDL window");
    }
    // Single-threaded init: must call renderFrame before init on threads where
    // bgfx will own the context. Skipped here — we run single-threaded throughout
    // (especially required on emscripten).
    bgfx::renderFrame();

    bgfx::Init init;
    init.platformData = pd;
#ifdef __EMSCRIPTEN__
    init.type = bgfx::RendererType::OpenGLES;
#else
    init.type = bgfx::RendererType::Count; // auto-pick
#endif
    init.resolution.width = fb_width;
    init.resolution.height = fb_height;
    init.resolution.reset = cfg.vsync ? BGFX_RESET_VSYNC : BGFX_RESET_NONE;
    if (!bgfx::init(init)) {
        throw std::runtime_error("bgfx::init failed");
    }

    bgfx::setViewClear(k_view_scene, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH, 0x202830ff, 1.0f, 0);
    bgfx::setViewRect(k_view_scene, 0, 0, bgfx::BackbufferRatio::Equal);
}

void App::Impl::init_imgui() {
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO &io = ImGui::GetIO();
    io.IniFilename = nullptr; // don't write imgui.ini next to the binary
    ImGui::StyleColorsDark();

    if (!ImGui_ImplSDL3_InitForOther(window)) {
        throw std::runtime_error("ImGui_ImplSDL3_InitForOther failed");
    }
    if (!ImGui_Implbgfx_Init(k_view_imgui)) {
        throw std::runtime_error("ImGui_Implbgfx_Init failed");
    }
}

void App::Impl::init_geometry() {
    static const PosColorVertex k_verts[] = {
        {0.0f, 0.5f, 0.0f, 0xff0000ff},   // top, red
        {0.5f, -0.5f, 0.0f, 0xff00ff00},  // bottom-right, green
        {-0.5f, -0.5f, 0.0f, 0xffff0000}, // bottom-left, blue
    };
    static const uint16_t k_indices[] = {0, 1, 2};

    const bgfx::VertexLayout layout = pos_color_layout();
    vbh = bgfx::createVertexBuffer(bgfx::makeRef(k_verts, sizeof(k_verts)), layout);
    ibh = bgfx::createIndexBuffer(bgfx::makeRef(k_indices, sizeof(k_indices)));

    const bgfx::RendererType::Enum type = bgfx::getRendererType();
    program =
        bgfx::createProgram(bgfx::createEmbeddedShader(k_solid_shaders, type, "vs_solid"),
                            bgfx::createEmbeddedShader(k_solid_shaders, type, "fs_solid"), true);
    if (!bgfx::isValid(program)) {
        throw std::runtime_error("Failed to create solid shader program");
    }
}

void App::Impl::shutdown() {
    if (bgfx::isValid(program)) {
        bgfx::destroy(program);
    }
    if (bgfx::isValid(vbh)) {
        bgfx::destroy(vbh);
    }
    if (bgfx::isValid(ibh)) {
        bgfx::destroy(ibh);
    }
    // Release scene_renderer's bgfx handles before bgfx::shutdown so they
    // don't survive into a destructor that runs against a dead context.
    scene_renderer.release();
    ImGui_Implbgfx_Shutdown();
    ImGui_ImplSDL3_Shutdown();
    ImGui::DestroyContext();
    bgfx::shutdown();
    if (window != nullptr) {
        SDL_DestroyWindow(window);
        window = nullptr;
    }
    SDL_Quit();
}

void App::Impl::poll_events() {
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
        ImGui_ImplSDL3_ProcessEvent(&ev);
        switch (ev.type) {
        case SDL_EVENT_QUIT:
            quit = true;
            break;
        case SDL_EVENT_WINDOW_CLOSE_REQUESTED:
            if (ev.window.windowID == SDL_GetWindowID(window)) {
                quit = true;
            }
            break;
        default:
            break;
        }
    }
}

void App::Impl::resize_if_needed() {
    int w = 0, h = 0;
    SDL_GetWindowSizeInPixels(window, &w, &h);
    if (w <= 0 || h <= 0) {
        return;
    }
    const uint32_t uw = static_cast<uint32_t>(w);
    const uint32_t uh = static_cast<uint32_t>(h);
    if (uw == fb_width && uh == fb_height) {
        return;
    }
    fb_width = uw;
    fb_height = uh;
    bgfx::reset(fb_width, fb_height, cfg.vsync ? BGFX_RESET_VSYNC : BGFX_RESET_NONE);
    bgfx::setViewRect(k_view_scene, 0, 0, bgfx::BackbufferRatio::Equal);
}

void App::Impl::render() {
    bgfx::touch(k_view_scene);

    if (scene) {
        // Lazy upload + frame-bounds: deferred until we have a live bgfx
        // context (App might be set_scene'd before init completes — although
        // currently we set_scene after construction, the lazy path is cheap
        // and robust against future call-order changes).
        if (!scene_uploaded) {
            scene_renderer.upload(*scene);
            scene_uploaded = true;
        }
        if (!camera_framed) {
            glm::vec3 bmin{0.f}, bmax{0.f};
            if (scene_renderer.world_bounds(bmin, bmax)) {
                camera.frame_bounds(bmin, bmax);
                camera_framed = true;
            }
        }
        SceneRenderer::RenderFlags flags;
        flags.wireframe = wireframe;
        flags.cull_back = cull_back;
        scene_renderer.render(k_view_scene, camera, fb_width, fb_height, flags);
        return;
    }

    // Fallback: Stage 1 demo triangle. Same path as before — kept for
    // running the viewer with no scene attached.
    const bgfx::Caps *caps = bgfx::getCaps();
    float view[16];
    float proj[16];
    const bx::Vec3 eye = {0.f, 0.f, -3.f};
    const bx::Vec3 at = {0.f, 0.f, 0.f};
    const bx::Vec3 up = {0.f, 1.f, 0.f};
    bx::mtxLookAt(view, eye, at, up);
    bx::mtxProj(proj, 60.0f, static_cast<float>(fb_width) / static_cast<float>(fb_height), 0.1f,
                100.f, caps->homogeneousDepth);
    bgfx::setViewTransform(k_view_scene, view, proj);

    const float t = static_cast<float>(SDL_GetTicks()) * 0.001f;
    float mtx[16];
    bx::mtxRotateY(mtx, t * 0.6f);
    bgfx::setTransform(mtx);

    bgfx::setVertexBuffer(0, vbh);
    bgfx::setIndexBuffer(ibh);
    bgfx::setState(BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A | BGFX_STATE_WRITE_Z |
                   BGFX_STATE_DEPTH_TEST_LESS | BGFX_STATE_MSAA);
    bgfx::submit(k_view_scene, program);
}

void App::Impl::update_camera_input() {
    if (!scene) {
        return;
    }
    ImGuiIO &io = ImGui::GetIO();
    // Don't consume mouse drags that ImGui captured (e.g. dragging the FPS
    // panel). Wheel always passes through — typical for inspection viewers.
    if (!io.WantCaptureMouse) {
        const ImVec2 d = io.MouseDelta;
        // Left-drag: orbit. Sensitivity tuned by feel; 0.005 rad/px ≈ ~180°
        // across a 600px window which feels right for inspection.
        if (io.MouseDown[0]) {
            camera.orbit(d.x * 0.005f, d.y * 0.005f);
        }
        // Middle-drag: pan. Pan speed scales with zoom distance so pixels
        // map to roughly consistent world-space motion at any range.
        if (io.MouseDown[2]) {
            const float scale = camera.distance * 0.001f;
            camera.pan(-d.x * scale, d.y * scale);
        }
    }
    if (io.MouseWheel != 0.f) {
        // 1.1^wheel: each notch = 10% closer/further. Matches Blender feel.
        camera.dolly(std::pow(1.1f, -io.MouseWheel));
    }
}

void App::Impl::tick() {
    poll_events();
    resize_if_needed();

    ImGui_Implbgfx_NewFrame();
    ImGui_ImplSDL3_NewFrame();
    ImGui::NewFrame();

    update_camera_input();

    {
        // Update FPS roughly once per second.
        const uint64_t now = SDL_GetTicks();
        ++frame_count;
        if (last_fps_tick == 0) {
            last_fps_tick = now;
        }
        if (now - last_fps_tick >= 1000) {
            fps =
                static_cast<float>(frame_count) * 1000.f / static_cast<float>(now - last_fps_tick);
            frame_count = 0;
            last_fps_tick = now;
        }
    }

    ImGui::Begin("nodehammer viewer");
    ImGui::Text("Backbuffer: %u x %u", fb_width, fb_height);
    ImGui::Text("Renderer: %s", bgfx::getRendererName(bgfx::getRendererType()));
    ImGui::Text("FPS: %.1f", fps);
    if (scene) {
        ImGui::Separator();
        ImGui::Text("Meshes: %u", scene_renderer.mesh_asset_count());
        ImGui::Text("Nodes: %u", scene_renderer.node_count());
        ImGui::Text("Tris (scene): %llu",
                    static_cast<unsigned long long>(scene_renderer.triangle_count()));
        const auto fs = scene_renderer.last_frame_stats();
        ImGui::Text("Draw calls: %u  Instances: %u  Tris/frame: %llu", fs.draw_calls, fs.instances,
                    static_cast<unsigned long long>(fs.triangles));
        if (ImGui::Button("Frame scene")) {
            glm::vec3 bmin{0.f}, bmax{0.f};
            if (scene_renderer.world_bounds(bmin, bmax)) {
                camera.frame_bounds(bmin, bmax);
            }
        }
        ImGui::Separator();
        if (ImGui::Checkbox("bgfx debug stats", &show_debug_stats)) {
            bgfx::setDebug(show_debug_stats ? BGFX_DEBUG_STATS : BGFX_DEBUG_NONE);
        }
        ImGui::Checkbox("backface cull", &cull_back);
        (void)wireframe; // wireframe mode currently disabled — see scene_renderer.cpp
        ImGui::Text("Camera: yaw=%.1f° pitch=%.1f° dist=%.2f", glm::degrees(camera.yaw),
                    glm::degrees(camera.pitch), camera.distance);
        ImGui::Text("        near=%.3f far=%.1f", camera.near_plane, camera.far_plane);
    } else {
        ImGui::Text("(no scene loaded — drawing demo triangle)");
    }
    ImGui::End();

    render();

    ImGui::Render();
    ImGui_Implbgfx_RenderDrawData(ImGui::GetDrawData());

    bgfx::frame();
}

void App::set_scene(std::shared_ptr<const RenderScene> scene) {
    impl_->scene = std::move(scene);
    impl_->scene_uploaded = false;
    impl_->camera_framed = false;
}

App::App(Config cfg) : impl_(std::make_unique<Impl>(std::move(cfg))) {
    impl_->init_sdl();
    impl_->init_bgfx();
    impl_->init_imgui();
    impl_->init_geometry();
}

App::~App() {
    if (impl_) {
        impl_->shutdown();
    }
}

int App::run() {
#ifdef __EMSCRIPTEN__
    // simulate_infinite_loop=1 unwinds main() with an exception so the runtime
    // keeps the wasm instance + GL context alive between frames. Requires
    // -fwasm-exceptions, which is set globally for emscripten builds.
    //
    // The unwind tears down every local on the way out, including any App
    // sitting on the caller's stack — so we'd hit a dangling Impl on the next
    // tick. Detach impl_ so the wasm runtime owns it for the lifetime of the
    // page; the App destructor then becomes a no-op on the emscripten path.
    Impl *leaked = impl_.release();
    emscripten_set_main_loop_arg(&App::Impl::em_tick, leaked, 0, 1);
    return 0; // unreachable: simulate_infinite_loop=1 throws past this
#else
    while (!impl_->quit) {
        impl_->tick();
    }
    return 0;
#endif
}

} // namespace nodehammer::viewer
