#include "imgui_impl_bgfx.hpp"

// Suppress renderer profiles we never compile (see shader_embed comment in
// app.cpp for rationale). Must be set before bgfx/embedded_shader.h is pulled.
#define BGFX_PLATFORM_SUPPORTS_DXBC 0
#define BGFX_PLATFORM_SUPPORTS_DXIL 0
#define BGFX_PLATFORM_SUPPORTS_NVN 0
#define BGFX_PLATFORM_SUPPORTS_PSSL 0
#define BGFX_PLATFORM_SUPPORTS_WGSL 0

#include <bgfx/bgfx.h>
#include <bgfx/embedded_shader.h>
#include <bx/math.h>
#include <bx/platform.h>
#include <imgui.h>

#include <cstring>

// Per-profile bytecode arrays generated by shaders/CMakeLists.txt
// (bgfx_compile_shaders ... AS_HEADERS). Each header defines static const
// uint8_t arrays named e.g. vs_imgui_essl[], fs_imgui_glsl[], etc. that the
// BGFX_EMBEDDED_SHADER table references at link time.
#if BGFX_PLATFORM_SUPPORTS_GLSL
#include "glsl/fs_imgui.sc.bin.h"
#include "glsl/vs_imgui.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_ESSL
#include "essl/fs_imgui.sc.bin.h"
#include "essl/vs_imgui.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_SPIRV
#include "spirv/fs_imgui.sc.bin.h"
#include "spirv/vs_imgui.sc.bin.h"
#endif
#if BGFX_PLATFORM_SUPPORTS_METAL
#include "metal/fs_imgui.sc.bin.h"
#include "metal/vs_imgui.sc.bin.h"
#endif

namespace nodehammer::viewer {

namespace {

const bgfx::EmbeddedShader k_embedded_shaders[] = {
    BGFX_EMBEDDED_SHADER(vs_imgui),
    BGFX_EMBEDDED_SHADER(fs_imgui),
    BGFX_EMBEDDED_SHADER_END(),
};

struct State {
    uint8_t view_id{255};
    bgfx::ProgramHandle program = BGFX_INVALID_HANDLE;
    bgfx::TextureHandle font_texture = BGFX_INVALID_HANDLE;
    bgfx::UniformHandle s_tex = BGFX_INVALID_HANDLE;
    bgfx::VertexLayout vertex_layout;
};

State g_state;

} // namespace

bool ImGui_Implbgfx_Init(uint8_t view_id) {
    g_state.view_id = view_id;

    g_state.vertex_layout.begin()
        .add(bgfx::Attrib::Position, 2, bgfx::AttribType::Float)
        .add(bgfx::Attrib::TexCoord0, 2, bgfx::AttribType::Float)
        .add(bgfx::Attrib::Color0, 4, bgfx::AttribType::Uint8, true)
        .end();

    const bgfx::RendererType::Enum type = bgfx::getRendererType();
    g_state.program =
        bgfx::createProgram(bgfx::createEmbeddedShader(k_embedded_shaders, type, "vs_imgui"),
                            bgfx::createEmbeddedShader(k_embedded_shaders, type, "fs_imgui"), true);

    g_state.s_tex = bgfx::createUniform("s_tex", bgfx::UniformType::Sampler);

    ImGuiIO &io = ImGui::GetIO();
    unsigned char *pixels = nullptr;
    int width = 0, height = 0;
    io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height);
    g_state.font_texture =
        bgfx::createTexture2D(static_cast<uint16_t>(width), static_cast<uint16_t>(height), false, 1,
                              bgfx::TextureFormat::BGRA8, 0,
                              bgfx::copy(pixels, static_cast<uint32_t>(width * height * 4)));
    io.Fonts->SetTexID(static_cast<ImTextureID>(g_state.font_texture.idx));

    return bgfx::isValid(g_state.program);
}

void ImGui_Implbgfx_Shutdown() {
    if (bgfx::isValid(g_state.font_texture)) {
        bgfx::destroy(g_state.font_texture);
        g_state.font_texture = BGFX_INVALID_HANDLE;
    }
    if (bgfx::isValid(g_state.s_tex)) {
        bgfx::destroy(g_state.s_tex);
        g_state.s_tex = BGFX_INVALID_HANDLE;
    }
    if (bgfx::isValid(g_state.program)) {
        bgfx::destroy(g_state.program);
        g_state.program = BGFX_INVALID_HANDLE;
    }
    ImGuiIO &io = ImGui::GetIO();
    io.Fonts->SetTexID(static_cast<ImTextureID>(0));
}

void ImGui_Implbgfx_NewFrame() {
    // Nothing per-frame; texture and program are persistent.
}

void ImGui_Implbgfx_RenderDrawData(ImDrawData *draw_data) {
    if (draw_data == nullptr || draw_data->CmdListsCount == 0) {
        return;
    }

    const float fb_width = draw_data->DisplaySize.x * draw_data->FramebufferScale.x;
    const float fb_height = draw_data->DisplaySize.y * draw_data->FramebufferScale.y;
    if (fb_width <= 0.f || fb_height <= 0.f) {
        return;
    }

    bgfx::setViewName(g_state.view_id, "ImGui");
    bgfx::setViewMode(g_state.view_id, bgfx::ViewMode::Sequential);

    const bgfx::Caps *caps = bgfx::getCaps();
    {
        const float L = draw_data->DisplayPos.x;
        const float R = draw_data->DisplayPos.x + draw_data->DisplaySize.x;
        const float T = draw_data->DisplayPos.y;
        const float B = draw_data->DisplayPos.y + draw_data->DisplaySize.y;
        float ortho[16];
        bx::mtxOrtho(ortho, L, R, B, T, 0.0f, 1000.0f, 0.0f, caps->homogeneousDepth);
        bgfx::setViewTransform(g_state.view_id, nullptr, ortho);
        bgfx::setViewRect(g_state.view_id, 0, 0, static_cast<uint16_t>(fb_width),
                          static_cast<uint16_t>(fb_height));
    }

    const ImVec2 clip_off = draw_data->DisplayPos;
    const ImVec2 clip_scale = draw_data->FramebufferScale;

    for (int n = 0; n < draw_data->CmdListsCount; ++n) {
        const ImDrawList *cmd_list = draw_data->CmdLists[n];

        const uint32_t num_vertices = static_cast<uint32_t>(cmd_list->VtxBuffer.Size);
        const uint32_t num_indices = static_cast<uint32_t>(cmd_list->IdxBuffer.Size);

        if (bgfx::getAvailTransientVertexBuffer(num_vertices, g_state.vertex_layout) <
                num_vertices ||
            bgfx::getAvailTransientIndexBuffer(num_indices) < num_indices) {
            // Not enough room — skip this draw list rather than crash.
            break;
        }

        bgfx::TransientVertexBuffer tvb;
        bgfx::TransientIndexBuffer tib;
        bgfx::allocTransientVertexBuffer(&tvb, num_vertices, g_state.vertex_layout);
        bgfx::allocTransientIndexBuffer(&tib, num_indices, sizeof(ImDrawIdx) == 4);
        std::memcpy(tvb.data, cmd_list->VtxBuffer.Data, num_vertices * sizeof(ImDrawVert));
        std::memcpy(tib.data, cmd_list->IdxBuffer.Data, num_indices * sizeof(ImDrawIdx));

        for (int ci = 0; ci < cmd_list->CmdBuffer.Size; ++ci) {
            const ImDrawCmd &cmd = cmd_list->CmdBuffer[ci];
            if (cmd.UserCallback != nullptr) {
                cmd.UserCallback(cmd_list, &cmd);
                continue;
            }

            const ImVec2 clip_min((cmd.ClipRect.x - clip_off.x) * clip_scale.x,
                                  (cmd.ClipRect.y - clip_off.y) * clip_scale.y);
            const ImVec2 clip_max((cmd.ClipRect.z - clip_off.x) * clip_scale.x,
                                  (cmd.ClipRect.w - clip_off.y) * clip_scale.y);
            if (clip_max.x <= clip_min.x || clip_max.y <= clip_min.y) {
                continue;
            }

            const uint16_t x = static_cast<uint16_t>(bx::max(clip_min.x, 0.f));
            const uint16_t y = static_cast<uint16_t>(bx::max(clip_min.y, 0.f));
            const uint16_t w =
                static_cast<uint16_t>(bx::min(clip_max.x, fb_width) - bx::max(clip_min.x, 0.f));
            const uint16_t h =
                static_cast<uint16_t>(bx::min(clip_max.y, fb_height) - bx::max(clip_min.y, 0.f));
            bgfx::setScissor(x, y, w, h);

            const uint64_t state =
                BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A | BGFX_STATE_MSAA |
                BGFX_STATE_BLEND_FUNC(BGFX_STATE_BLEND_SRC_ALPHA, BGFX_STATE_BLEND_INV_SRC_ALPHA);
            bgfx::setState(state);

            bgfx::TextureHandle tex = g_state.font_texture;
            if (cmd.GetTexID() != 0) {
                tex.idx = static_cast<uint16_t>(cmd.GetTexID());
            }
            bgfx::setTexture(0, g_state.s_tex, tex);

            bgfx::setVertexBuffer(0, &tvb, 0, num_vertices);
            bgfx::setIndexBuffer(&tib, cmd.IdxOffset, cmd.ElemCount);
            bgfx::submit(g_state.view_id, g_state.program);
        }
    }
}

} // namespace nodehammer::viewer
