#!/usr/bin/env python3
"""Build a self-describing `.nhproj` project archive from a fixture scene.

A `.nhproj` is a plain zip working set (see `ZipWorkingSet`) whose root
`nodehammer.toml` carries a `[project]` section naming the entry config and
geometry keys — that is what makes it "just build" when the viewer opens it,
with no extension-based guessing (`App::Impl::applyProjectManifest`).

The archive assembled here mirrors what the viewer's *Publish package* produces
by hand, so a CI-published page and a user-published one have the same shape:

    nodehammer.toml      # [project] config = ..., geometry = ...
    <scene>.toml         # entry config
    odd/*.toml           # its transitive `include` chain, keys preserved
    odd.nhb.zst          # geometry blob

The zip is written deterministically (fixed timestamps, sorted entries), so the
same inputs always hash to the same name — the archive is named
`project.<content-hash>.nhproj` so republishing cache-busts for free while an
unchanged publication keeps its URL.

`nodehammer project pack` is the shipped way to build one of these, and produces
the same shape from the same `buildArchiveWorkingSet` walk. This script stays for
the wasm dev loop and the Pages build, which run against an Emscripten tree
without necessarily having a native `nodehammer` binary to call — and which want
the content-hashed name that `pack` does not generate.

Usage:
    scripts/make_nhproj.py <scene> <out-dir>

`scene` names any `fixtures/configs/<scene>.toml`. The archive file name is
printed on stdout.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIGS_DIR = ROOT / "fixtures" / "configs"
GEOMETRY = ROOT / "odd.nhb.zst"

# Zip timestamps are part of the bytes we hash, so pin them. 1980-01-01 is the
# earliest a zip can represent.
FIXED_DATE = (1980, 1, 1, 0, 0, 0)

# Matches `include = "a.toml"` or `include = ["a.toml", "b.toml"]` at the top
# level of a config. Good enough for these fixtures' plain quoted strings — the
# same approximation the C++ side's include walk is fed by, not a TOML parser.
INCLUDE_RE = re.compile(r'^\s*include\s*=\s*(\[[^\]]*\]|"[^"]*")', re.MULTILINE | re.DOTALL)


def collect_includes(rel: str, seen: list[str]) -> None:
    """Depth-first walk of `rel`'s include chain, appending keys to `seen`.

    Keys are relative to `fixtures/configs/`, which is also the archive's key
    space: an include is resolved against the *including* file's directory, so
    keeping the fixture layout keeps include resolution working inside the
    archive unchanged.
    """
    if rel in seen:
        return
    path = CONFIGS_DIR / rel
    if not path.is_file():
        sys.exit(f"config include not found: {rel}")
    seen.append(rel)

    parent = Path(rel).parent
    match = INCLUDE_RE.search(path.read_text(encoding="utf-8"))
    if not match:
        return
    for inc in re.findall(r'"([^"]*)"', match.group(1)):
        if inc:
            collect_includes(str(parent / inc) if str(parent) != "." else inc, seen)


def build_archive(scene: str) -> bytes:
    """Serialize the scene's archive to zip bytes."""
    if not (CONFIGS_DIR / f"{scene}.toml").is_file():
        sys.exit(f"unknown scene '{scene}' — no fixtures/configs/{scene}.toml")
    if not GEOMETRY.is_file():
        sys.exit(f"geometry blob not found: {GEOMETRY}")

    config_key = f"{scene}.toml"
    geometry_key = GEOMETRY.name

    seen: list[str] = []
    collect_includes(config_key, seen)

    manifest = (
        "# Generated by scripts/make_nhproj.py — the archive's project manifest.\n"
        "[project]\n"
        f'config = "{config_key}"\n'
        f'geometry = "{geometry_key}"\n'
    )

    entries: dict[str, bytes] = {"nodehammer.toml": manifest.encode("utf-8")}
    for rel in seen:
        entries[rel] = (CONFIGS_DIR / rel).read_bytes()
    entries[geometry_key] = GEOMETRY.read_bytes()

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for key in sorted(entries):
            info = zipfile.ZipInfo(key, date_time=FIXED_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, entries[key])
    return buf.getvalue()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("scene", help="fixture scene name (fixtures/configs/<scene>.toml)")
    parser.add_argument("out_dir", type=Path, help="directory to write the archive into")
    args = parser.parse_args()

    blob = build_archive(args.scene)
    name = f"project.{hashlib.sha256(blob).hexdigest()[:16]}.nhproj"

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / name).write_bytes(blob)
    print(name)


if __name__ == "__main__":
    main()
