# Turn `skills/<name>/**` into one C++ translation unit of byte arrays.
#
# Run in script mode (`cmake -P`) by a custom command, not included by the main
# build. Inputs, all required:
#
#   NH_SKILLS_DIR    the `skills/` directory the paths below are relative to
#   NH_SKILLS_FILES  ;-list of absolute paths, globbed at configure time
#   NH_SKILLS_OUT    the .cpp to write
#
# Why embedding rather than installing the files and finding them at run time:
# the same `cli::run` serves the executable and the Python wheel, and under the
# wheel the running executable is the interpreter -- so an install-tree guess
# resolves to the wrong prefix entirely. src/web/runtime_locator.hpp is the
# search ladder that exists because the wasm runtime *cannot* be embedded (it is
# megabytes, built by another toolchain). A skill is kilobytes of text built by
# nobody, so it goes in the binary and there is no locator to get wrong, no
# packaging knob per ecosystem, and no way for a development install to differ
# from a released one.
#
# Deliberately uncompressed. zstd is already linked, but nothing that runs at
# *build* time can compress: CMake has no zstd, and a host tool built from the
# library would have to be cross-built twice over (Emscripten, and cibuildwheel's
# manylinux container). Measured, it would save single-digit kilobytes against a
# 12 MB binary. Plain bytes also survive `strings`, which is how you answer "did
# the skill actually get embedded" without running anything.

cmake_minimum_required(VERSION 3.25)

foreach(var NH_SKILLS_DIR NH_SKILLS_OUT)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "GenerateSkillsData.cmake: ${var} is required")
    endif()
endforeach()

# Not in the loop above: an empty list is a legitimate input (a build with no
# skills yet), and `if(NOT DEFINED)` cannot tell that from a caller that forgot.
if(NOT DEFINED NH_SKILLS_FILES)
    set(NH_SKILLS_FILES "")
endif()

# ── Group the files by the directory that names their skill ───────────────────
#
# `skills/<name>/<relative/path>`: the first segment is the skill's name, the
# rest is the path it keeps when installed. Nested paths matter -- a skill with
# a `references/` tree is the normal shape, not an edge case -- so this walks
# whatever the glob found rather than assuming one SKILL.md per directory.
set(skill_names "")
foreach(path IN LISTS NH_SKILLS_FILES)
    file(RELATIVE_PATH rel "${NH_SKILLS_DIR}" "${path}")
    string(FIND "${rel}" "/" slash)
    if(slash EQUAL -1)
        # A loose file directly under skills/ belongs to no skill. A README
        # explaining the directory is the likely one; skipping beats guessing.
        continue()
    endif()
    string(SUBSTRING "${rel}" 0 ${slash} name)
    math(EXPR rest_start "${slash} + 1")
    string(SUBSTRING "${rel}" ${rest_start} -1 rest)

    if(NOT name IN_LIST skill_names)
        list(APPEND skill_names "${name}")
        set(skill_${name}_paths "")
        set(skill_${name}_sources "")
    endif()
    list(APPEND skill_${name}_paths "${rest}")
    list(APPEND skill_${name}_sources "${path}")
endforeach()

# Sorted so the generated file -- and therefore `skills list` -- does not depend
# on the order the filesystem happened to hand back.
list(SORT skill_names)

set(out "// GENERATED by cmake/GenerateSkillsData.cmake -- do not edit.\n")
string(APPEND out "//\n")
string(APPEND out "// The contents of skills/ at build time. Regenerated whenever one of those\n")
string(APPEND out "// files changes; edit the SKILL.md, never this.\n\n")
# Angle brackets and a src-relative path, the spelling every other in-tree
# include uses: this file is generated into the *binary* directory, so a
# quoted "skills_data.hpp" would be looked for next to itself and not found.
string(APPEND out "#include <cli/skills_data.hpp>\n\n")
string(APPEND out "namespace nodehammer::cli::detail {\nnamespace {\n\n")

# Identifiers are numbered, never derived from the skill's name.
#
# `kFiles_${name}` was the obvious spelling and it is wrong: a skill directory
# called `nodehammer-config` produced `kFiles_nodehammer-config`, which a C++
# compiler reads as a subtraction. Sanitizing the name would work until two
# names sanitized to the same identifier. An index cannot collide and cannot be
# ill-formed, and the name survives where it actually belongs -- in the string
# literal that `skills list` prints.
set(file_index 0)
set(skill_index 0)
foreach(name IN LISTS skill_names)
    set(entries "")
    set(paths ${skill_${name}_paths})
    set(sources ${skill_${name}_sources})
    list(LENGTH paths count)
    math(EXPR last "${count} - 1")
    foreach(i RANGE 0 ${last})
        list(GET paths ${i} rel)
        list(GET sources ${i} src)

        file(READ "${src}" hex HEX)
        string(LENGTH "${hex}" hex_length)
        math(EXPR byte_count "${hex_length} / 2")

        if(byte_count EQUAL 0)
            # A zero-length array is ill-formed in C++, so an empty file gets one
            # padding byte and a recorded length of 0. The span is empty either
            # way; this only keeps the declaration legal.
            set(body "0x00,")
        else()
            # Two passes rather than a MATCHALL and a foreach: a 13 KB file is
            # 13000 list elements, and iterating those in CMake is seconds.
            # Chunks are exactly 32 hex characters, so no byte pair ever
            # straddles an inserted newline.
            string(REGEX REPLACE "(................................)" "\\1\n" chunked "${hex}")
            string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," body "${chunked}")
        endif()

        string(APPEND out "// skills/${name}/${rel}\n")
        string(APPEND out "constexpr unsigned char kBytes${file_index}[] = {\n${body}\n};\n\n")
        list(APPEND entries "    {\"${rel}\", {kBytes${file_index}, ${byte_count}U}},")
        math(EXPR file_index "${file_index} + 1")
    endforeach()

    string(REPLACE ";" "\n" entries_text "${entries}")
    string(APPEND out "// skills/${name}/\n")
    string(APPEND out "constexpr EmbeddedFile kFiles${skill_index}[] = {\n${entries_text}\n};\n\n")
    set(skill_${name}_ident "kFiles${skill_index}")
    math(EXPR skill_index "${skill_index} + 1")
endforeach()

list(LENGTH skill_names skill_count)
if(skill_count EQUAL 0)
    # Same rule as the empty file above, one level up: no table at all rather
    # than an empty one, and the accessor returns an empty span.
    string(APPEND out "} // namespace\n\n")
    string(APPEND out "std::span<const EmbeddedSkill> embeddedSkills() { return {}; }\n\n")
else()
    set(rows "")
    foreach(name IN LISTS skill_names)
        list(LENGTH skill_${name}_paths n)
        list(APPEND rows "    {\"${name}\", {${skill_${name}_ident}, ${n}U}},")
    endforeach()
    string(REPLACE ";" "\n" rows_text "${rows}")
    string(APPEND out "constexpr EmbeddedSkill kSkills[] = {\n${rows_text}\n};\n\n")
    string(APPEND out "} // namespace\n\n")
    string(APPEND out "std::span<const EmbeddedSkill> embeddedSkills() { return kSkills; }\n\n")
endif()

string(APPEND out "} // namespace nodehammer::cli::detail\n")

# Only when it differs. Ninja reruns this command whenever an input is newer than
# the output, and rewriting an identical file would recompile the translation
# unit -- and everything that links it -- for nothing.
set(previous "")
if(EXISTS "${NH_SKILLS_OUT}")
    file(READ "${NH_SKILLS_OUT}" previous)
endif()
if(NOT previous STREQUAL out)
    file(WRITE "${NH_SKILLS_OUT}" "${out}")
else()
    file(TOUCH "${NH_SKILLS_OUT}")
endif()
