execute_process(
    COMMAND git describe --tags --long --always
    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
    OUTPUT_VARIABLE _git_describe
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE _git_result
)

if(_git_result EQUAL 0 AND _git_describe MATCHES
        "^v([0-9]+)\\.([0-9]+)\\.([0-9]+)-([0-9]+)-g([0-9a-f]+)$")
    set(NODEHAMMER_VERSION_MAJOR "${CMAKE_MATCH_1}")
    set(NODEHAMMER_VERSION_MINOR "${CMAKE_MATCH_2}")
    set(NODEHAMMER_VERSION_PATCH "${CMAKE_MATCH_3}")
    if(CMAKE_MATCH_4 EQUAL 0)
        set(NODEHAMMER_VERSION
            "${NODEHAMMER_VERSION_MAJOR}.${NODEHAMMER_VERSION_MINOR}.${NODEHAMMER_VERSION_PATCH}")
    else()
        set(NODEHAMMER_VERSION
            "${NODEHAMMER_VERSION_MAJOR}.${NODEHAMMER_VERSION_MINOR}.${NODEHAMMER_VERSION_PATCH}-${CMAKE_MATCH_4}-g${CMAKE_MATCH_5}")
    endif()
else()
    set(NODEHAMMER_VERSION_MAJOR 0)
    set(NODEHAMMER_VERSION_MINOR 0)
    set(NODEHAMMER_VERSION_PATCH 0)
    set(NODEHAMMER_VERSION "0.0.0")
endif()
